---
language: c

sudo: false

cache: ccache

env:
  global:
  - TRAVIS_COMMIT_MSG="${TRAVIS_COMMIT_MSG:-$(git log --format=%B --no-merges -n1)}"
  #- CCACHE=ccache
  # Coverity hack to disable Coverity by default unless [ci coverity] was specified in commit message
  - TRAVIS_PULL_REQUEST="$((echo $TRAVIS_PULL_REQUEST | grep -q 'false' && echo $TRAVIS_COMMIT_MSG | grep -qE '\[ci (scan|cov(erity)?)\]') && echo -n false || echo -n true)"
  - secure: "DEXcC9CT8pneavqbNgiAtq1v59E3KZn2AlLYdfhzRa6W2k5lr7yyf+21rCczK1YvMt9hjGkKMMTthU/huHF774t/LK0IEtXAh+HjdiQpRQhiYl7jGT4SD5fSfkMlIwGUtLJixp8I5ny8W/OOCiOf1ARpHyPd1K55WuUyaIwCl6k="
  - secure: "GkMTrWzbkV4fxji32DtCwvUELBWSHKo9GKzuqL4JdVUpvYraLVT/jMfRKMdceUcE+a88l0ZL6CXqLz/aA8qp6ULY5MXxgCMmrPYqzewpjbvtvoxcedrsu9wue3kpe2MzgGz7yg5/Kf0Rj8ejMLa1ZSyAa9TlCody5pIzRVJAPMk="
  # certificate for tag releases
  - secure: nEd22lqGEnA0FSLfsoS/NwTWTqYcAPUMjM5QyJDkxWm1jXb3AScfQKhoLV+Mb1TbZIOpCQNHFUx2mVMCHQyRtx3MlkDiNyFwt9D5VWiF8tNWUS4hX0XHI6NnW5UYqqGtuXZNwNvWBIJqDhOJH6fkUfD+fjG3ANKSQX1K+Of3PZY=
  - secure: NQbryvM0ff6ZncpyslLT3uoa2IeOUDDj4FWLJj0vmIz7GSE9Ja7INUsJ6HUu0QmsqfgnJ8/TSIje0hLz7OGQLhcVXCGMIYjeUIUPA4kVV8KnQonFHOI4R5F+7VO93EW29LYcvfGojuInAP4y9mxqKoQcMEsx9ImCl6QvUf/+WaM=

addons:
  apt:
    packages:
    # travis default: sudo aptitude install git git-svn ruby rubygems ruby-json
    # travis setup: sudo aptitude install gcc-multilib g++-multilib binutils-mingw-w64-i686 gcc-mingw-w64-i686 g++-mingw-w64-i686 binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 p7zip-full autoconf libcurl4-openssl-dev
    # 32bit gcc (for AutoVersion)
    - gcc-multilib
    - g++-multilib
    # 32bit MinGW
    - binutils-mingw-w64-i686
    - gcc-mingw-w64-i686
    - g++-mingw-w64-i686
    # 64bit MinGW
    - binutils-mingw-w64-x86-64
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    # tag release
    - p7zip-full
    - autoconf
    - libcurl4-openssl-dev
    # testing
    #- wine
  coverity_scan:
    project:
      name: White-Tiger/T-Clock
      description: Build submitted via Travis CI
    notification_email:
      secure: Guqbi+ipUVfFpkJZsyrzMqmVqFA6dJKnhGau/FB/RcvLWRZD6hdArZlECRe9gQHjTg82gPOqwMjOmLlDQjWEXUua93E3dxTAAkiHVyweocKF2W7bAqhVKD6FB1bwcpA7CV/n5InvqfvFnhp/4J3kyb9qRFGPjaWcUiw7z4fFuqk=
    build_command_prepend: |
      which ccache
      which i686-w64-mingw32-gcc
      cov-configure --compiler=i686-w64-mingw32-gcc --comptype=gcc --template
      cov-configure --compiler=x86_64-w64-mingw32-gcc --comptype=gcc --template
      ccache --clear
      ./compile.bat clean
    build_command: . compile.bat
    branch_pattern: ".*"

deploy:
  provider: releases
  api_key:
    secure: SxspqObGcVCG8bpDS/aHtAYSl30mAiTWl+KcpWBET1rTwqOnnVSU/G86ylFMURpvXams8IT8+ld3m7uqINwnhwmzmIXtdECVI9LKgD7T1cgaZyK03TMzRfnXsW4EnpjVYnfwuYnioom3LH2FdBR3zLJuyxSq8OSrrkSFJ7BqQxM=
  file_glob: true
  file:
  - Release/T-Clock*.7z
  - Release/T-Clock*.zip
  skip_cleanup: true
  on:
    tags: true

before_script: # also before Coverity
- pushd src
script:
- . compile.bat
after_success:
- ./sign-n-zip.bat
- popd
